version: "3.0"
services:
  react:
    network_mode: "host"
    restart: always
    build:
      context: .
      dockerfile: prod/Dockerfile_front
      args:
        - VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}
        - VITE_CLIENT_ID=${VITE_CLIENT_ID}
        - VITE_REDIRECT_URI=${VITE_REDIRECT_URI}
        - VITE_BASE_URL=${VITE_BASE_URL}
  node:
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLIENT_ID=${CLIENT_ID}
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
      dockerfile: prod/Dockerfile_back
    ports:
      - "3003:3003"
    networks:
      - web
    volumes:
      - ./back/src:/home/node/app/src
networks:
  web:
    driver: bridge
volumes:
  pgdata:
