FROM node:18-alpine

USER root
COPY back/ /home/node/app
WORKDIR /home/node/app
RUN rm -rf node_modules package-lock.json build && chown -R node:node /home/node/app
USER node

RUN npm install

CMD npm start
